### ISSUE TITLE
Text changing colour support?

### ISSUE THREAD

**Issue by iAlborz** [Creatide/AnimateMate#10]
I've tried changing the colour of the text from frame to frame, but it changed the colour on every frame instead. not sure if colour change is supported for objects or not. but having the support would be nice. The ability to change fill colour and stroke colour both would be nice as well.

**Comment by niittymaa** [comment]
Animating colors isn't supported in current version. This is because, it supports only values that every item can have (layer or groups). So text or item coloring is some specific that only certain elements can have.

One way to control colors is using opacity values and animating those. And don't forget using blending modes combined with opacity animations. Of course it's not so precise but in some cases it could work.
