### ISSUE TITLE
plugin crashes in sketch 3.8 - El Capitan

### ISSUE THREAD

**Issue by HaYesSeattle** [Creatide/AnimateMate#14]
is anyone else having this issue? I love this plugin, but I can't export without a freeze/crash.

**Comment by niittymaa** [comment]
It could feel like it's freeze because it's uses OSX own commands in background. So if you try to export longer or bigger animations it's freeze sketch until it's done in background. I've used it only with El Capitan without problems. Best way to see if it's work, is to export PNG sequence and if you got images it works. Remember that GIF exporter takes much longer time with conversion with long animations, because it export first PNGs and then combine those to animated GIF. Say if this helps. 

So the answer is, it should work with El Capitan, it just take some time and there is no indicator about process (I do not know yet how to make it properly) :)

**Comment by HaYesSeattle** [comment]
ahhh - OK, that is good to know. 
I waited about 5 minutes...so maybe my file is too big and/or my animation is too long. I wasn't doing anything super fancy - but it is a design for a large screen so the file is big.

**Comment by niittymaa** [comment]
Thanks for your kindly words! I hope I'll find more time to make it even better based on feedback.
