### ISSUE TITLE
Bugs, No Scrollbar and Enterproblem in Edit Animation Window

### ISSUE THREAD

**Issue by janstieler** [Creatide/AnimateMate#17]
Hi,
first, nice plugin!
I have the problem that I don't get a scrollbar if I have a lot of keyframes and if I press the enter button it will not generate a new line, it will close the window.
Theese both things are not so smart for a good usability.

Cheers

**Comment by niittymaa** [comment]
You're absolutely right about usability. It's not the best part of this plugin. I need to investigate more about how to make better UI to Sketch plugin and that way to make it easier to use. It could take time because I do not know so much about that topic... For now you can create new lines in textboxes by pressing "Alt + Enter".

**Comment by janstieler** [comment]
Thanks!
