### ISSUE TITLE
When exporting element go away

### ISSUE THREAD

**Issue by JacquelinClement** [Creatide/AnimateMate#18]
Hello,

I can't test this plugin because when i export my artboard my element with animation go away.
The layer that must be animated still fly away and i can't see it in the animation ...

Do you know why ?

**Comment by niittymaa** [comment]
Sounds that it could be the problem with groups like in this issue https://github.com/Creatide/AnimateMate/issues/8

This happens when you use groups. To avoid that you need to use "bounds" layer that is bigger than actual animated item. I mention that in this video if I remember right :) https://www.youtube.com/watch?v=bDm_c4wPBkc 

If it's something else you can send me source file to hello@creatide.com
