### ISSUE TITLE
Plugin Jams Sketch to a Halt?

### ISSUE THREAD

**Issue by Harkko** [Creatide/AnimateMate#22]
The whole Sketch application became unresponsive after installing this plugin. Tried to restart system & open again to no avail. Removed this plugin and reinstalled Sketch and everything worked again.

Sketch v. 41.2 (35397), OS X 10.11.6. I can share crash logs from the system if needed.

**Comment by niittymaa** [comment]
I've tested it now with Sketch v. 41.2 (35397), OS X 10.12.2 and AnimateMate 0.1.7.
It seems to work properly. Only different version of my setup is OSX, so hard to say if it's because of that. And I do not have way to test it out now with downgraded OSX version :(

Is it happened to you only when exporting GIF? If so then reason could be SIP command in plugin.

Here is fast test output GIF.
![test](https://cloud.githubusercontent.com/assets/4587998/21802469/8a7b77e4-d72e-11e6-9cb8-eb422053708b.gif)

**Comment by niittymaa** [comment]
Also if it's only "freeze" while exporting then it could be like this https://github.com/Creatide/AnimateMate/issues/14

But if it's crashes Sketch when starting application, then it's new thing.

**Comment by Harkko** [comment]
Ok, sorry about the fuss, but everything started working ok after Sketch reinstall. Only thing I can think of: had Sketch app running the first time while I installed the plugin. Did the install again when Sketch was closed and everything seems to work ok now!

**Comment by niittymaa** [comment]
No problem at all. It's still good to know that all because it could happen again for someone :)
