### ISSUE TITLE
exporting animation breaks views

### ISSUE THREAD

**Issue by XavierOlland** [Creatide/AnimateMate#23]
I create my animation as usual but when I start the export the animated frames just disappear...
They are still there in sketch's layer list but not graphically here, and they don't appear in the animation either.

Sketch version : 41.2

**Comment by niittymaa** [comment]
Sounds that it could be the problem with groups like in this issue https://github.com/Creatide/AnimateMate/issues/8

This happens when you use groups. To avoid that you need to use "bounds" layer that is bigger than actual animated item. I mention that in this video if I remember right :) https://www.youtube.com/watch?v=bDm_c4wPBkc
