### ISSUE TITLE
Gradients don't export correctly

### ISSUE THREAD

**Issue by davemoz** [Creatide/AnimateMate#30]
While testing this plugin I tried to recreate the Facebook loading animation (having a masked, gradient-filled "highlight" rectangle animate across some UI elements) and noticed that the gradient doesn't export correctly when exporting _as a gif_. See here: https://www.dropbox.com/s/tsew3buks4ybfxt/animateMate-gradientFail.gif?dl=0

**Comment by niittymaa** [comment]
It could be because of GIF compression. Have you tested out with exporting PNG sequence? If PNG looks ok, then it's gif compression. Using gradients in GIF images is not easiest, because there is limited amount of colors in gif... AnimateMate uses [Gifsicle](https://www.lcdf.org/gifsicle/) library.

Tip: There is great free app to playback PNG sequences http://djv.sourceforge.net/

**Comment by davemoz** [comment]
Thanks, I did end up resorting to using a PNG sequence and re-exporting from Photoshop as a gif.
