### ISSUE TITLE
New way of storing animation information

### ISSUE THREAD

**Issue by iAlborz** [Creatide/AnimateMate#5]
The current method of saving the information in the layer name is not the best. I remember other plug-ins that solves this by putting those informations in the layer description and not title. (or something similar. I'm not a developer, but I read the issue on another plug-in and the solution was explained like this)

**Comment by niittymaa** [comment]
You're right. This is something that have already pointed out in closed issues. It will change after got more visual way to show that layer have animation. Need more advanced GUI like in Craft or similar plugins. This is something that is currently under progress, but it's now smallest task :) For now this is closed issue because the way it works now is based how it works. If you hide those properties under the hood, user will confused about where layers have animation and where not.

**Comment by iAlborz** [comment]
That makes a lot of sense. great!
