### ISSUE TITLE
New option for changing ease type

### ISSUE THREAD

**Issue by iAlborz** [Creatide/AnimateMate#6]
The current method of changing ease type from 'create animation' isn't the most intuitive way.

**Comment by niittymaa** [comment]
True. Now there is three way to change it. Manually by writing it, creating new animation, or checking that checkbox there. And this is most intuitive of those :) I think this is something that belongs to the "Edit Animation" menu. Because you're editing exist animation. But this is something that left there for the reason how I've used those animations, if it's under edit menu it will limit editing to one layer by time. Another reason was that I wanted to change all easing types fast to random easing types while creating keyframes. Thanks for pointing this one.

**Comment by iAlborz** [comment]
Just to be clear, I was thinking of adding the option to change ease type here:

<img width="233" alt="screen shot 2016-03-29 at 9 41 19 am" src="https://cloud.githubusercontent.com/assets/4399410/14116011/9ad3c4ee-f592-11e5-8603-8c9d0a609287.png">

You're right though, changing it one by one is different from changing the whole thing.
